### ISSUE TITLE
Ejercicios en equipo_Diego_Mayra_Felix_Daniel

### ISSUE THREAD

**Issue by Felix-Angel** [SistemasTecTlaxiaco/actividad-5-practica-de-conjuntos-equipo-mayra-diego-daniel-felix#1]
[PRACTICA_MATE_DISCRETAS_EQUIPO_DIEGO_MAYRA_FELIX_ALEJANDRO.pdf](https://github.com/SistemasTecTlaxiaco/actividad-5-practica-de-conjuntos-equipo-mayra-diego-daniel-felix/files/12753163/PRACTICA_MATE_DISCRETAS_EQUIPO_DIEGO_MAYRA_FELIX_ALEJANDRO.pdf)

**Comment by 23620031** [comment]
ELEMENTOS DE PORTADA -> 25/25
PROCEDIMIENTO -> 25/25
FIGURAS, ILUSTRACIONES Y FOTOGRAFÍAS -> 25/25
RESULTADOS Y CONCLUCIONES -> 22/25 (faltan la descripción de resultados)

TOTAL=19.4/20

 CALIFICADO POR EL EQUIPO DE LÓPEZ DOMÍNGUEZ

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
